library(stats)
library(psych)
library(foreign)
library(InformationValue)
library(caret)
train =  read.spss('/Users/gautamborgohain/Google Drive/Datasets/Caravan_train_0.sav',use.value.labels = FALSE,to.data.frame = TRUE)
test =  read.spss('/Users/gautamborgohain/Google Drive/Datasets/Caravan_test_0.sav',use.value.labels = FALSE,to.data.frame = TRUE)
train$CARAVAN <- as.factor(train$CARAVAN)
model = train(CARAVAN~., data = train, method = 'logreg')
pred = predict(model,test)
confusionMatrix(pred,test$CARAVAN)
